spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://lslm.live:3306/buckmoo?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1Lslm.live$
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      driver-class-name: com.mysql.cj.jdbc.Driver
      min-idle: 5
      max-active: 50
      max-wait: 50000
      time-between-eviction-runs-millis: 50000
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: 1Lslm.live$
  jackson:
    default-property-inclusion: non_null
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl

server:
  servlet:
    context-path: /newbuckmoo
  port: 80

wechat:
  mpAppId: njfhrohakdheuhde
  mpAppSecret: 78397534251111121
  mchId: 7829714nidoheiofreo
  mchKey: lhl1212321312312hl1ftbhalshdjkcr2345
  mchPath: D:\develop\wechatPayKey\apiclient_cert.p12
  notifyUrl: http://lslm.live/newbuckmoo/all-pay/notify
  templateId:
    auditResult: ruHAwxC-rtOVvFv2121ib9LSNtr_ldqioTKfM2qpwf1gYXc
    newRegister: GGyGLHKgw1dnO7a12OlnDkR2NOR9y1Vq7K5w6EbIpqSr4
    recharge: jSLsYp-V6t1dItOFXu211111111ldcJY9CJfF6HT9uevxamBQQ3c
    notFinishPay: 7C66Nl9OI2qYP1Wy_OF2WjB_dRO08ZvxnYbMbEDOA0c

aliyun:
  regionId: cn-hangzhou
  accessKeyId: 2134332111111111111111125345233443
  secret: 6KIoQ89301829038212222222229401l23

projecturl:
  wechatMpAuthorize: http://ls12lm.live
  newbuckmoo: http://l.comde.iv0e/21new2121bu21c21k21moo
  websocket: lslswsqw21212100m.l21imove:80