spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://lslm.live:3306/buckmoo?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1Lslm.live$
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      driver-class-name: com.mysql.cj.jdbc.Driver
      min-idle: 5
      max-active: 50
      max-wait: 50000
      time-between-eviction-runs-millis: 50000
  jpa:
    show-sql: true
  mvc:
    static-path-pattern: /**
  redis:
    host: 127.0.0.1
    port: 6379
    password: 1Lslm.live$
  jackson:
    default-property-inclusion: non_null
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl

server:
  servlet:
    context-path: /newbuckmoo
  port: 80

wechat:
  mpAppId: wxb39b42f5fd93c167
  mpAppSecret: 3d63c96f84e4587baa5e4a6f85d1a515
  mchId: 1545797881
  mchKey: lhl123456anxlhl123456anxlhl12345
  mchPath: D:\develop\wechatPayKey\apiclient_cert.p12
  notifyUrl: http://lslm.live/newbuckmoo/allpay/notify
  templateId:
    auditResult: ruHAwxC-rtOVvFvib9LSNtr_ldqioTKfM2qpwf1gYXc

aliyun:
  regionId: cn-hangzhou
  accessKeyId: LTAIAlvA2P2ekeha
  secret: 6KIoQD2X33V78JSYbp0wGLaUMUm18l

projecturl:
  wechatMpAuthorize: http://lslm.live
  newbuckmoo: http://lslm.live/newbuckmoo
  websocket: lslm.live:80